name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project with Maven
        run: ./mvnw clean package
      - name: Build the Docker image
        run: docker build -t simple-java .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login
      - name: Tag image
        run:
          docker tag simple-java registry.digitalocean.com/enigmacamp/simple-java:${{ github.event.inputs.version }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/enigmacamp/simple-java:${{ github.event.inputs.version }}

